// Generated by CoffeeScript 1.6.3
/*
	* @param {*=} initial_value
	* @param {function(current, previous, index, array)} callback
*/


(function() {
  Array.prototype.narrow = function(initial_value, callback) {
    var _ref;
    if (callback == null) {
      _ref = [initial_value, null], callback = _ref[0], initial_value = _ref[1];
    }
    return this.reduce(callback, initial_value);
  };

}).call(this);
