// Generated by CoffeeScript 1.6.3
(function() {
  var command, parse;

  parse = require('./parse');

  command = require('./command');

  /*
  	* Get version.
  	*
  	* @param {function(?err, result)} callback
  */


  exports.get = function(callback) {
    return command.exec('--version', '', function(err, code, output) {
      if (err) {
        return callback(err);
      }
      if (code > 0) {
        return callback(new Error("cannot get version"));
      }
      if (callback) {
        return callback(null, parse.version_info(output));
      }
    });
  };

}).call(this);
